trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    docker-compose -f docker-compose.yaml up -d
    displayName: 'Run Docker Compose'

- task: AzureCLI@2
  inputs:
    azureSubscription: '<Azure-Service-Connection>'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az vm start --name VM1 --resource-group <Resource-Group>
