# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: ReactJS
          demands:
            - VM1
        steps:
          - script: docker compose -f docker-compose.yaml up -d
            displayName: build step