# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - script: docker compose -f docker-compose.yaml up -d
            target: VM1
